name: mymambaenv
channels:
  - defaults
  - conda-forge
dependencies:
  - numba
  - tqdm
  - h5py
  - pandas
  - scipy
  - cmake=3.14
  - swig=4.0.2
  - matplotlib
  - cfitsio
  - yaml
  - pexpect
  - pymysql
  - astroplan
